### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by draxyolo** [MD3XTER/Twitch-Farmer#14]
Traceback (most recent call last):
  File "twitch_farmer.py", line 254, in <module>
    main()
  File "twitch_farmer.py", line 134, in main
    run_driver(True)
  File "twitch_farmer.py", line 210, in run_driver
    current_proxy = find_available_proxy()
  File "twitch_farmer.py", line 178, in find_available_proxy
    proxies_csv = pandas.read_csv(proxies_csv_path, sep=',', dtype="str")
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 702,      in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 435,      in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1139,      in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1995,      in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.     read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader.     _read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader.     _read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader.     _tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_pars     er_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in      line 3, saw 5

root@WearyInternal-VM:/home/bot/Twitch-Farmer# pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in      line 3, saw 5

How do I fix this?

**Comment by MD3XTER** [comment]
Can you please share with me your data files, it seems like bot can't read that data.

**Comment by draxyolo** [comment]
How do I send them to you?

**Comment by MD3XTER** [comment]
other the files in a text editor and paste it here

**Comment by MD3XTER** [comment]
I am gonna assume that you have fixed your problem, so I will close this issue right now. Feel free to open a new issue if you have any other problems!
