### ISSUE TITLE
Error when launching bot

### ISSUE THREAD

**Issue by AlexClander** [MD3XTER/Twitch-Farmer#22]
I receive the following error when trying to start the bot:

```
Using proxy: [XXX.XXX.XXX.175:3128]
Traceback (most recent call last):
  File "twitch_farmer.py", line 254, in <module>
    main()
  File "twitch_farmer.py", line 134, in main
    run_driver(True)
  File "twitch_farmer.py", line 231, in run_driver
    executable_path=chrome_driver_path)
  File "/home/twitch/Twitch-Farmer/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/twitch/Twitch-Farmer/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/twitch/Twitch-Farmer/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/twitch/Twitch-Farmer/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/twitch/Twitch-Farmer/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-148-generic x86_64)

```

Followed the steps on the installation guide, but created a new non-root user and created a virtualenv for python3.7 (deadsnakes repository, as im using ubuntu 16.04 and python 3.7 is not supported on default packages):

```
sudo adduser twitch

su twitch

cd

git clone https://github.com/MD3XTER/Twitch-Farmer.git

virtualenv -p /usr/bin/python3.7 Twitch-Farmer

source Twitch-Farmer/bin/activate

cd Twitch-Farmer

pip3 install selenium pandas

python3 twitch_farmer.py
```

What am I missing? Thank you for your work MD3XTER

**Comment by OttoX4** [comment]
Did you install google chrome?
I did the same as you (but ubuntu 18.04) and received similar error messages until I installed Chrome.
