### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by davidevalle** [MD3XTER/Twitch-Farmer#28]
Hi so when I start the bot I get No internet
and an error: ERR_PROXY_CONNECTION_FAILED

**Comment by andrei-zgirvaci** [comment]
It means usually that the proxy you have specified is bad, try other proxies

**Comment by davidevalle** [comment]
I tried that already I always get:
````
Using proxy: [xxx.xxx.x.197:80]

DevTools listening on ws://127.0.0.1:57179/devtools/browser/863ae512-aff8-492b-bec8-6baba11bfbce
[27gameryt2] Singing in...
Traceback (most recent call last):
  File "twitch_farmer.py", line 254, in <module>
    main()
  File "twitch_farmer.py", line 136, in main
    sign_in_status = sign_in(username, password)
  File "twitch_farmer.py", line 74, in sign_in
    driver.get("https://www.twitch.tv/login")
  File "C:\Users\vdavi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\vdavi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\vdavi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=85.0.4183.83)


C:\Users\vdavi\Desktop\Twitch-Farmer>[18504:21128:0909/235402.211:ERROR:device_event_log_impl.cc(208)] [23:54:02.212] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.`
```

**Comment by andrei-zgirvaci** [comment]
Are you using public or private proxies?

**Comment by eqMFqfFd** [comment]
> Are you using public or private proxies?

Private proxies. Same issue here.

**Comment by JamesonWelch** [comment]
Private proxies confirmed to work on other libs and getting same issue here.

**Comment by JamesonWelch** [comment]
I had the same issue but was able to fix it. Sometimes your proxy service requires credentials or that your IP is whitelisted. If creds are needed, simply adding the proxy argument won't work. Also, many proxy services rotate proxy endpoints so make sure that hasn't happened.

**Comment by BenthosBacon** [comment]
wtf was macht ihr in meinen mails?

Jameson ***@***.***> schrieb am Mi. 2. Juni 2021 um 18:36:

**Comment by houssemaydi** [comment]
i got the same problem :(
