### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by holdenc20** [MD3XTER/Twitch-Farmer#4]
Traceback (most recent call last):
  File "Twitch-Farmer.py", line 163, in <module>
    SetUp(proxies[proxy_count], username, password)
  File "Twitch-Farmer.py", line 15, in SetUp
    driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"B057B7CD5B054C2543B4285B9BFFDA4D","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.12.6 x86_64)

**Comment by holdenc20** [comment]
Ok I fixed the setup error and now it is giving me this message
Traceback (most recent call last):
  File "Twitch-Farmer.py", line 163, in <module>
    SetUp(proxies[proxy_count], username, password)
  File "Twitch-Farmer.py", line 15, in SetUp
    driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 490, in _request
    resp = self._conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by MD3XTER** [comment]
As I see the problem is in the selenium, it can't run the chrome driver, I don't know exactly what is causing the error but If I was you, I would reinstall everything and make sure everything is as in the installation.

The project is deprecated and I don't have time now to dig dipper into the problem and fix it. But thanks for notifying me about the issue. I hope you can fix it and if you do, please also pull a request with the fix, It will be much appreciated! 👍

**Comment by MD3XTER** [comment]
@holdenc20 It's been a while since your issue but I have just released the 2.0 version, have a look and see if you have that issue anymore.
