### ISSUE TITLE
Error with windowspath

### ISSUE THREAD

**Issue by cristiangutie** [MD3XTER/Twitch-Farmer#9]
Can anyone help me with this problem please?

Using proxy: [109.190.171.107:4145]
Traceback (most recent call last):
  File "twitch_farmer.py", line 244, in <module>
    main()
  File "twitch_farmer.py", line 135, in main
    run_driver(True)
  File "twitch_farmer.py", line 221, in run_driver
    executable_path=chrome_driver_path)
  File "C:\Users\**\scoop\apps\python\current\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\**\scoop\apps\python\current\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\**\scoop\apps\python\current\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\**\scoop\apps\python\current\lib\subprocess.py", line 1100, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\**\scoop\apps\python\current\lib\subprocess.py", line 511, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by MD3XTER** [comment]
@cristiangutie Thanks for informing me, I just push a new commit [4f94199](https://github.com/MD3XTER/Twitch-Farmer/commit/4f941994bf3f8f618de40776e6458c133c9dcac9) that should fix the problem.

**Comment by MD3XTER** [comment]
@cristiangutie It should be fixed now [7daa27a](https://github.com/MD3XTER/Twitch-Farmer/commit/7daa27a640f8cb3877077e9cc729972394bbbaa8)

**Comment by cristiangutie** [comment]
@MD3XTER Thanks, its working now.

**Comment by MD3XTER** [comment]
@cristiangutie Great! Let me know if you have any more issues!
